---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: site/content/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: site/static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: npm run preview
  publish_command: npm run build
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.54.0
  - baseurl=https://yesimaaron.github.io/let-us-be-your-lungs-dev/
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
